name: Zip and Release Visual Studio template

on:
  push:
    branches:
      - 'main'

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4
    - name: Zip repository contents
      run: zip -r "Haste Steam Workshop Mod.zip" ../
    - name: Archive zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: zipped-vstemplate
        path: app/build/outputs/apk/stable/release
  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write
    steps:
      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: zipped-vstemplate
          path: vstemplate
      - name: Create draft release and upload template zip
        uses: actions/github-script@v7
        with:
          script: |
            const path = require('node:path');
            const fs = require('node:fs/promises');

            const release = await github.rest.repos.createRelease({
              ... context.repo,
              name: 'Visual Studio Template (${{ github.ref_name }})',
              draft: true,
              tag_name: '${{ github.ref_name }}',
              generate_release_notes: true
            });

            console.log('Draft release created:', release.data.html_url);

            for await (const filePath of (await glob.create('vstemplate/*')).globGenerator()) {
              const fileName = path.basename(filePath);

              console.log(`Uploading ${fileName} asset to draft release`);

              const data = await fs.readFile(filePath);
              await github.rest.repos.uploadReleaseAsset({
                ... context.repo,
                release_id: release.data.id,
                name: fileName,
                data
              });

              console.log(`${fileName} asset uploaded to draft release`);
            }
