name: Zip and Release Visual Studio template

on:
  push:
    branches:
      - 'main'

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4
      with:
        path: ./template
    - name: Convert to Visual Studio template
      run: |
        cat << EOF > ./template/HasteSteamWorkshopMod.vstemplate
        <VSTemplate Version="3.0.0" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" Type="Project">
          <TemplateData>
            <Name>Haste Steam Workshop Mod</Name>
            <ProjectType>CSharp</ProjectType>
            <ProjectSubType>
            </ProjectSubType>
            <SortOrder>1000</SortOrder>
            <CreateNewFolder>true</CreateNewFolder>
            <DefaultName>Haste Steam Workshop Mod</DefaultName>
            <ProvideDefaultName>true</ProvideDefaultName>
            <LocationField>Enabled</LocationField>
            <EnableLocationBrowseButton>true</EnableLocationBrowseButton>
            <CreateInPlace>true</CreateInPlace>
          </TemplateData>
          <TemplateContent>
            <Project TargetFileName="Haste$projectname$Mod.csproj" File="HasteExampleMod.csproj" ReplaceParameters="true">
              <ProjectItem ReplaceParameters="true" TargetFileName=".gitignore">.gitignore</ProjectItem>
              <ProjectItem ReplaceParameters="false" TargetFileName=".steam.props">.steam.props</ProjectItem>
              <ProjectItem ReplaceParameters="true" TargetFileName="$projectname$.cs">Example.cs</ProjectItem>
              <ProjectItem ReplaceParameters="false" TargetFileName="LICENSE">LICENSE</ProjectItem>
            </Project>
          </TemplateContent>
        </VSTemplate>
        EOF

        rm -fr ./template/.git
        rm -fr ./template/.github
    - name: Zip repository contents
      run: |
        mkdir -p ./zipped-vstemplate
        zip -r ./zipped-vstemplate/HasteSteamWorkshopMod.zip ./template/*
    - name: Archive zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: zipped-vstemplate
        path: ./zipped-vstemplate
  release:
    runs-on: ubuntu-latest
    needs: [ zip ]
    permissions:
      contents: write
    steps:
      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: zipped-vstemplate
          path: vstemplate
      - name: Get short SHA of latest commit
        id: get_git_head_short_sha
        run: echo "result=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create draft release and upload template zip
        uses: actions/github-script@v7
        with:
          script: |
            const path = require('node:path');
            const fs = require('node:fs/promises');

            const release = await github.rest.repos.createRelease({
              ... context.repo,
              name: `Visual Studio Template (commit ${{ steps.get_git_head_short_sha.outputs.result }})`,
              draft: true,
              tag_name: `${{ github.ref_name }}-${{ steps.get_git_head_short_sha.outputs.result }}`,
              generate_release_notes: true
            });

            console.log('Draft release created:', release.data.html_url);

            for await (const filePath of (await glob.create('vstemplate/*')).globGenerator()) {
              const fileName = path.basename(filePath);

              console.log(`Uploading ${fileName} asset to draft release`);

              const data = await fs.readFile(filePath);
              await github.rest.repos.uploadReleaseAsset({
                ... context.repo,
                release_id: release.data.id,
                name: fileName,
                data
              });

              console.log(`${fileName} asset uploaded to draft release`);
            }
